#install.packages("smotefamily")
#install.packages("caret")
#install.packages("ROSE")
library(smotefamily)
library(caret)
library(ROSE)

# simulate data
# where each dataset has different parameters
# (size of the dataset and proportion of rare examples over all examples)


# data <- sample_generator(n, ratio = 0.8, xlim = c(0, 1), ylim = c(0, 1), radius = 0.25, overlap = -0.05, outcast_ratio = 0.01)
# The function to generate 2-dimensional dataset given the number of instances and the ratio between
# the number of negative instances to total instances. The positive instances will be distributed 
# uniformly as the circle in the center while negative instances are around over the domain.
# The random positive outcasts are also generated. The dataset is used to show the difference 
# between datasets generated by each sampling technique.


###############################################################################

# balance dataset with SMOTE

# data.smote <- SMOTE(X, target, K = 5, dup_size = 0)

# balance dataset with SMOTE variant
# (train set is different, but test set is the same)


###############################################################################
#apply models (tree and logistic regression) to datasets

# tree.smote <- rpart(y ~ ., data = data.smote)
# tree.smote.dirichlet <- rpart(y ~ ., data = data.smote.dirichlet)
# pred.tree.smote <- predict(tree.smote, newdata = data.test)
# pred.tree.smote.dirichlet <- predict(tree.smote.dirichlet, newdata = data.test)

###############################################################################
#compute metrics to compare our variant to the original technique
# roc.curve(data.test$cls, pred.tree.smote[,2])
# roc.curve(data.test$cls, pred.tree.smote.dirichlet[,2], add.roc = TRUE, col = 2, lty = 2)

